# This workflow deploys the application to Vercel when changes are pushed to the main branch.

name: Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: dergim
          envVariableKeys: BACKEND_URL
        env:
          BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}
          BACKEND_CLIENT_ID: ${{ secrets.BACKEND_CLIENT_ID }}
          BACKEND_CLIENT_SECRET: ${{ secrets.BACKEND_CLIENT_SECRET }}
          TARGET_BACKEND_URL: preview,development,production
          TYPE_BACKEND_URL: encrypted

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
